name: Build Casio App

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake libusb-1.0-0-dev libpng-dev python3-pip git pkg-config libudisks2-dev
          pip3 install pillow --break-system-packages

      - name: Install GiteaPC
        run: |
          git clone https://git.planet-casio.com/Lephenixnoir/GiteaPC.git
          cd GiteaPC
          yes | python3 giteapc.py install Lephenixnoir/GiteaPC

      - name: Install Casio Toolchain (Takes 15-20 mins)
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          yes | giteapc install Lephenixnoir/fxsdk:noudisks2
          yes | giteapc install Lephenixnoir/sh-elf-gcc
          yes | giteapc install Lephenixnoir/gint

      - name: Compile App
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          fxsdk build-fx

      - name: Upload .g1a File
        uses: actions/upload-artifact@v4
        with:
          name: serial-test-app
          path: '*.g1a'
